// Nomos Analytics — Demo Data
// Source: Matin (2026), "The Capital Velocity Gap" — Working Paper, Katz Graduate School of Business
// All DCR figures derived from IRS Form 990 (ProPublica Nonprofit Explorer) and Federal Audit Clearinghouse Single Audit data.
window.NOMOS = window.NOMOS || {};

window.NOMOS.orgs = [
  {
    id: "innovation-works",
    name: "Innovation Works, Inc.",
    state: "PA",
    city: "Pittsburgh",
    type: "Ben Franklin Technology Partner",
    sector: "Tech / Entrepreneurship",
    totalGrants: 14200000,
    totalGrantsLabel: "$14.2M",
    dcr: 0.25,
    dcrLabel: "25%",
    status: "flagged",
    risk: "HIGH",
    directDisbursementRate: 25,
    personnelCostShare: 49,
    boardReserves: 29000000,
    boardReservesLabel: "$29M",
    fy: "FY2024–2025",
    source: "IRS Form 990 / Federal Audit Clearinghouse",
    flags: [
      { code: "OVERHEAD-01", label: "Staff Compensation Exceeds Disbursements", detail: "Staff compensation ($7M+) now exceeds total disbursements to founders — a structural inversion of the intermediary's core mission." },
      { code: "RESERVE-01", label: "Excess Board-Designated Reserves", detail: "$29M in board-designated reserves against ~$14.2M annual receipts — a 204% reserve ratio with no public deployment timeline." },
      { code: "AUDIT-01", label: "Non-GAGAS Subsidiary", detail: "Subsidiary VC fund not audited under GAGAS standards, limiting independent verification of capital deployment claims." },
      { code: "CAPITAL-01", label: "Unverifiable Recycled Capital Claims", detail: "Recycled capital claims unverifiable under current audit scope. Cannot be independently confirmed from public filings." },
    ],
    financials: [
      { year: "FY2023", receipts: 12800000, disbursed: 3200000, personnel: 6200000, overhead: 3400000 },
      { year: "FY2024", receipts: 13600000, disbursed: 3400000, personnel: 6600000, overhead: 3600000 },
      { year: "FY2025", receipts: 14200000, disbursed: 3550000, personnel: 7000000, overhead: 3650000 },
    ],
    description: "Innovation Works is Pennsylvania's largest publicly-funded startup accelerator, administering BFTP funds across the Pittsburgh region. Staff compensation ($7M+) now exceeds total disbursements to founders — a structural inversion of the intermediary's core mission. DCR: 25%.",
    subsidiaries: ["AlphaLab Gear", "IW Capital Partners"],
    legislativeRefs: ["PA BFTP Program (Act 1988)", "Innovate in PA (Act 52 of 2013)"],
  },
  {
    id: "bftp-sep",
    name: "BFTP of Southeastern PA",
    state: "PA",
    city: "Philadelphia",
    type: "Ben Franklin Technology Partner",
    sector: "Tech / Life Sciences",
    totalGrants: 11800000,
    totalGrantsLabel: "$11.8M",
    dcr: 0.002,
    dcrLabel: "0.2%",
    status: "flagged",
    risk: "HIGH",
    directDisbursementRate: 0.2,
    personnelCostShare: 62,
    boardReserves: 8400000,
    boardReservesLabel: "$8.4M",
    fy: "FY2024–2025",
    source: "IRS Form 990 / Federal Audit Clearinghouse",
    flags: [
      { code: "OVERHEAD-01", label: "Near-Total Overhead Absorption", detail: "Management overhead almost entirely consumes state funding before it reaches founders. DCR of 0.2% represents near-complete 'dead money' — public capital retained within the intermediary's cost structure." },
      { code: "OVERHEAD-02", label: "Personnel Cost Dominance", detail: "62% of total expenditure consumed by personnel costs, leaving virtually nothing for direct capital deployment to founders." },
    ],
    financials: [
      { year: "FY2023", receipts: 10900000, disbursed: 22000, personnel: 6700000, overhead: 4178000 },
      { year: "FY2024", receipts: 11400000, disbursed: 23000, personnel: 7000000, overhead: 4377000 },
      { year: "FY2025", receipts: 11800000, disbursed: 24000, personnel: 7300000, overhead: 4476000 },
    ],
    description: "BFTP of Southeastern Pennsylvania presents the most extreme case of overhead absorption in the dataset. A 0.2% DCR means $99.80 of every $100 in state funding is retained for internal operations. The strongest evidence for the 'dead money' thesis.",
    subsidiaries: [],
    legislativeRefs: ["PA BFTP Program (Act 1988)"],
  },
  {
    id: "bftp-nep",
    name: "BFTP of Northeastern PA",
    state: "PA",
    city: "Bethlehem",
    type: "Ben Franklin Technology Partner",
    sector: "Manufacturing / Tech",
    totalGrants: 8200000,
    totalGrantsLabel: "$8.2M",
    dcr: 0.36,
    dcrLabel: "~36%",
    status: "review",
    risk: "MEDIUM",
    directDisbursementRate: 36,
    personnelCostShare: 38,
    boardReserves: 3100000,
    boardReservesLabel: "$3.1M",
    fy: "FY2024–2025",
    source: "IRS Form 990 / Federal Audit Clearinghouse",
    flags: [
      { code: "OVERHEAD-02", label: "Elevated Overhead vs. Deployment", detail: "Approved $5.28M for 86 companies in FY2025 — the highest company count in the BFTP network — yet heavy incubator overhead constrains capital efficiency." },
    ],
    financials: [
      { year: "FY2023", receipts: 7600000, disbursed: 2600000, personnel: 3000000, overhead: 2000000 },
      { year: "FY2024", receipts: 7900000, disbursed: 2800000, personnel: 3100000, overhead: 2000000 },
      { year: "FY2025", receipts: 8200000, disbursed: 2952000, personnel: 3100000, overhead: 2148000 },
    ],
    description: "BFTP-NEP approved $5.28M for 86 companies in FY2025 — the highest company count in the BFTP network — yet maintains heavy incubator overhead that depresses capital efficiency. Best-performing BFTP center, but still well below the 75% mandate threshold.",
    subsidiaries: [],
    legislativeRefs: ["PA BFTP Program (Act 1988)"],
  },
  {
    id: "jumpstart",
    name: "JumpStart Inc.",
    state: "OH",
    city: "Cleveland",
    type: "Innovation Intermediary",
    sector: "Tech / Entrepreneurship",
    totalGrants: 14900000,
    totalGrantsLabel: "$14.9M",
    dcr: 0.21,
    dcrLabel: "21%",
    status: "flagged",
    risk: "HIGH",
    directDisbursementRate: 21,
    personnelCostShare: 44,
    boardReserves: 6200000,
    boardReservesLabel: "$6.2M",
    fy: "FY2024",
    source: "IRS Form 990 (ProPublica Nonprofit Explorer)",
    flags: [
      { code: "OVERHEAD-01", label: "21% Direct Capital Ratio", detail: "79 cents of every dollar retained for internal operations. High 'consultant expenses' often represent internal service credits rather than liquid capital disbursed to founders." },
      { code: "ACCOUNTING-01", label: "Internal Service Credit Accounting", detail: "Reported consultant expenses include internal service credits, inflating apparent program activity without corresponding founder capital deployment." },
    ],
    financials: [
      { year: "FY2022", receipts: 13200000, disbursed: 2640000, personnel: 5700000, overhead: 4860000 },
      { year: "FY2023", receipts: 14100000, disbursed: 2820000, personnel: 6100000, overhead: 5180000 },
      { year: "FY2024", receipts: 14900000, disbursed: 3129000, personnel: 6500000, overhead: 5271000 },
    ],
    description: "JumpStart demonstrates Ohio's consistent '20% floor' problem — approximately 80 cents of every dollar is retained for internal operations. High consultant expenses often represent internal service credits rather than liquid capital reaching founders.",
    subsidiaries: [],
    legislativeRefs: ["Ohio ORC 5725.18 (Insurance Premium Tax Credit)"],
  },
  {
    id: "rev1",
    name: "Rev1 Ventures",
    state: "OH",
    city: "Columbus",
    type: "Innovation Intermediary",
    sector: "Tech / Entrepreneurship",
    totalGrants: 11100000,
    totalGrantsLabel: "$11.1M",
    dcr: 0.24,
    dcrLabel: "~24%",
    status: "flagged",
    risk: "HIGH",
    directDisbursementRate: 24,
    personnelCostShare: 41,
    boardReserves: 4800000,
    boardReservesLabel: "$4.8M",
    fy: "FY2024",
    source: "IRS Form 990 (ProPublica Nonprofit Explorer)",
    flags: [
      { code: "OVERHEAD-01", label: "~24% Direct Capital Ratio", detail: "$11.1M total expenses with approximately 24% deployment ratio — consistent with Ohio's systemic 20% floor pattern." },
      { code: "COMP-01", label: "Elevated Executive Compensation", detail: "Executive compensation totaling $785K represents a significant secondary overhead metric relative to total capital deployed to founders." },
    ],
    financials: [
      { year: "FY2022", receipts: 9800000, disbursed: 2156000, personnel: 4400000, overhead: 3244000 },
      { year: "FY2023", receipts: 10400000, disbursed: 2288000, personnel: 4700000, overhead: 3412000 },
      { year: "FY2024", receipts: 11100000, disbursed: 2664000, personnel: 4551000, overhead: 3885000 },
    ],
    description: "Rev1 Ventures confirms the Ohio pattern: $11.1M in total expenses with ~24% deployment. Executive compensation of $785K is a notable overhead line. No documented linkage between corporate tax incentives and startup procurement obligations.",
    subsidiaries: [],
    legislativeRefs: ["Ohio ORC 5725.18"],
  },
  {
    id: "invest-detroit",
    name: "Invest Detroit",
    state: "MI",
    city: "Detroit",
    type: "CDFI / Innovation Intermediary",
    sector: "Multi-sector",
    totalGrants: 22200000,
    totalGrantsLabel: "$22.2M",
    dcr: 0.45,
    dcrLabel: "~45%",
    status: "review",
    risk: "MEDIUM",
    directDisbursementRate: 45,
    personnelCostShare: 32,
    boardReserves: 9100000,
    boardReservesLabel: "$9.1M",
    fy: "FY2024",
    source: "IRS Form 990 (ProPublica Nonprofit Explorer)",
    flags: [
      { code: "OVERHEAD-02", label: "Elevated Salary Base", detail: "$7.1M in salaries representing 32.3% of total FY2024 expenses of $22.2M — above best-in-class benchmarks but better than PA peers." },
    ],
    financials: [
      { year: "FY2022", receipts: 19400000, disbursed: 8236000, personnel: 6300000, overhead: 4864000 },
      { year: "FY2023", receipts: 20800000, disbursed: 9360000, personnel: 6700000, overhead: 4740000 },
      { year: "FY2024", receipts: 22200000, disbursed: 9990000, personnel: 7100000, overhead: 5110000 },
    ],
    description: "Invest Detroit is Michigan's best-performing major intermediary at ~45% DCR. FY2024 total expenses: $22.2M, with $7.1M in salaries (32.3%). Higher deployment than PA peers, but still below the proposed 75% mandate threshold.",
    subsidiaries: [],
    legislativeRefs: ["Michigan Innovation Fund ($60M)", "MI MEDC Automotive/Mobility Initiative"],
  },
  {
    id: "ann-arbor-spark",
    name: "Ann Arbor SPARK",
    state: "MI",
    city: "Ann Arbor",
    type: "Regional Innovation Org",
    sector: "Tech / University Spinout",
    totalGrants: 11300000,
    totalGrantsLabel: "$11.3M",
    dcr: 0.203,
    dcrLabel: "20.3%",
    status: "flagged",
    risk: "HIGH",
    directDisbursementRate: 20,
    personnelCostShare: 48,
    boardReserves: 3800000,
    boardReservesLabel: "$3.8M",
    fy: "FY2024",
    source: "IRS Form 990 (ProPublica Nonprofit Explorer)",
    flags: [
      { code: "OVERHEAD-01", label: "20.3% Direct Capital Ratio", detail: "While SPARK assisted 457 startups, direct investment from managed funds totaled only $2.3M against $11.3M in total expenses — a 20.3% DCR." },
      { code: "OUTPUT-01", label: "Activity vs. Capital Deployment Gap", detail: "High startup assistance count (457) masks low capital deployment. 'Assistance' is not equivalent to capital — the DCR measures only direct investment." },
    ],
    financials: [
      { year: "FY2022", receipts: 9900000, disbursed: 1881000, personnel: 4700000, overhead: 3319000 },
      { year: "FY2023", receipts: 10600000, disbursed: 2012000, personnel: 5000000, overhead: 3588000 },
      { year: "FY2024", receipts: 11300000, disbursed: 2294900, personnel: 5424000, overhead: 3581100 },
    ],
    description: "Ann Arbor SPARK assisted 457 startups in FY2024 but direct investment from managed funds totaled only $2.3M — a 20.3% DCR. Illustrates how high activity counts can mask low capital efficiency. Total expenses: $11.3M.",
    subsidiaries: [],
    legislativeRefs: ["Michigan Innovation Fund"],
  },
  {
    id: "elevate-ventures",
    name: "Elevate Ventures",
    state: "IN",
    city: "Indianapolis",
    type: "Statewide Venture Dev. Org",
    sector: "Tech / Multi-sector",
    totalGrants: 18900000,
    totalGrantsLabel: "$18.9M",
    dcr: 0.55,
    dcrLabel: "55%",
    status: "compliant",
    risk: "LOW",
    directDisbursementRate: 55,
    personnelCostShare: 19,
    boardReserves: 2200000,
    boardReservesLabel: "$2.2M",
    fy: "FY2024",
    source: "IRS Form 990 (ProPublica Nonprofit Explorer)",
    flags: [],
    financials: [
      { year: "FY2022", receipts: 15200000, disbursed: 7904000, personnel: 2700000, overhead: 4596000 },
      { year: "FY2023", receipts: 17100000, disbursed: 9405000, personnel: 3000000, overhead: 4695000 },
      { year: "FY2024", receipts: 18900000, disbursed: 10395000, personnel: 3420000, overhead: 5085000 },
    ],
    description: "Elevate Ventures is the regional benchmark. In FY2024, Elevate maintained $10.8M in expenses while committing $18.9M in capital — a DCR of 55%, more than double the Pennsylvania BFTP network average of ~23%. Single statewide vehicle with unified reporting.",
    subsidiaries: [],
    legislativeRefs: ["Indiana VCI Tax Credit ($20M)", "CICP / AnalytiXIN pilot programs"],
  },
  {
    id: "wedc",
    name: "Wisconsin Economic Dev. Corp.",
    state: "WI",
    city: "Madison",
    type: "Quasi-Public Dev. Authority",
    sector: "Multi-sector",
    totalGrants: 197700000,
    totalGrantsLabel: "$197.7M",
    dcr: 0.20,
    dcrLabel: "~20%",
    status: "flagged",
    risk: "HIGH",
    directDisbursementRate: 20,
    personnelCostShare: 38,
    boardReserves: 22000000,
    boardReservesLabel: "$22M",
    fy: "FY2025",
    source: "WEDC FY2025 Annual Report",
    flags: [
      { code: "OVERHEAD-01", label: "~20% Direct Grant Ratio", detail: "Of $197.7M in total FY2025 contracts, only $39.1M were direct grants to businesses — a calculated DCR of approximately 20%." },
      { code: "ARCH-01", label: "CDE Intermediary Layer", detail: "New Community Development Entity (CDE) Investment Credit for insurance companies adds a CDE layer between tax dollars and operating businesses — replicating the intermediary problem without addressing root cause." },
    ],
    financials: [
      { year: "FY2023", receipts: 181000000, disbursed: 36200000, personnel: 68700000, overhead: 76100000 },
      { year: "FY2024", receipts: 189000000, disbursed: 37800000, personnel: 71800000, overhead: 79400000 },
      { year: "FY2025", receipts: 197700000, disbursed: 39100000, personnel: 75100000, overhead: 83500000 },
    ],
    description: "WEDC reported $197.7M in total FY2025 contracts but only $39.1M were direct grants to businesses — a ~20% DCR. New CDE legislation replicates the intermediary problem by inserting another overhead layer between insurance tax dollars and operating companies.",
    subsidiaries: ["Wisconsin Housing and Economic Development Authority"],
    legislativeRefs: ["WI CDE Investment Credit (2025)"],
  },
];

window.NOMOS.scenarios = {
  programName: "Innovate in PA 2.0",
  proposedBudget: 100000000,
  proposedBudgetLabel: "$100M",
  context: "Act 52 of 2013 sold $100M in deferred insurance premium tax credits to 29 qualified insurance companies at 87¢ on the dollar. No requirement for insurers to provide pilot contracts to funded startups.",
  scenarios: [
    {
      id: "A",
      label: "Status Quo",
      structure: "Pass as proposed — existing BFTP intermediary structure unchanged",
      dcr: 0.23,
      dcrLabel: "~23%",
      directToFounders: 23000000,
      directLabel: "$23M",
      feasibility: "High",
      risk: "Continued waste",
      timeline: "Immediate",
      color: "#555",
      detail: "Replicates current BFTP network average DCR of ~23%. Of $100M appropriated, approximately $23M reaches founders. $77M absorbed by overhead, reserves, and personnel — consistent with documented Innovation Works and BFTP-SEP patterns.",
    },
    {
      id: "B",
      label: "75% Direct Capital Mandate",
      structure: "Pittsburgh Compact: 75% floor on direct founder disbursements",
      dcr: 0.75,
      dcrLabel: "75%",
      directToFounders: 75000000,
      directLabel: "$75M",
      feasibility: "Medium",
      risk: "Intermediary resistance",
      timeline: "6–12 months",
      color: "#e8341a",
      detail: "A 75% Direct Capital Mandate would nearly triple capital reaching founders without any increase in appropriations. For every $10M allocated, $7.5M reaches founders vs. $2.3M today. Compliance verifiable via annual FAC filings. Requires intermediary restructuring — expect resistance from existing overhead structures.",
    },
    {
      id: "C",
      label: "Performance-Based + First Customer",
      structure: "Tranche by regional DCR + First Customer Clause for tax-incentivized corps",
      dcr: 0.52,
      dcrLabel: "~52%",
      directToFounders: 52000000,
      directLabel: "$52M",
      feasibility: "Medium-High",
      risk: "Implementation complexity",
      timeline: "3–6 months",
      color: "#f97316",
      detail: "Ties disbursement tranches to verified DCR scores, creating an accountability loop. Adds a First Customer Clause requiring corporations receiving >$10M in state tax incentives to pilot at least one product per year from a state-headquartered startup. Addresses both capital efficiency and market access — the Indiana CICP model.",
    },
  ],
};

window.NOMOS.keyStats = {
  avgDCR: 0.27,
  avgDCRLabel: "27¢",
  statesAnalyzed: 5,
  orgsAnalyzed: 9,
  worstDCR: { org: "BFTP-SEP", val: "0.2%" },
  bestDCR: { org: "Elevate Ventures (IN)", val: "55%" },
};

window.NOMOS.personas = [
  { id: "legislator", label: "State Legislator", sub: "Oversight & Appropriations", icon: "M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z" },
  { id: "foundation", label: "Foundation Officer", sub: "Due Diligence", icon: "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" },
  { id: "federal", label: "Federal Auditor", sub: "OIG / GAO", icon: "M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" },
  { id: "journalist", label: "Journalist", sub: "Investigative / Accountability", icon: "M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z M14 2v6h6 M16 13H8 M16 17H8 M10 9H8" },
];

window.NOMOS.suggestedQueries = [
  "Which intermediaries have a DCR below 25%?",
  "Compare BFTP-SEP to Elevate Ventures — what explains the gap?",
  "What would Innovate in PA 2.0 deliver to founders under each scenario?",
  "Which state has the most efficient innovation funding architecture?",
  "What are the red flags in the Innovation Works FY2025 audit?",
  "How does Pennsylvania's dual-track system compare to Indiana's single vehicle?",
];
